# Generated by Django 5.2.8 on 2025-11-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
