# Generated by Django 5.2.8 on 2025-11-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_access_user_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh',
        ),
    ]
